version: "3.7"
services:
  web:
    # コンテナ名
    container_name: web-wanto
    build:
        # 読み込むファイル名が`Dockerfile`ではない場合contextに相対パス、dockerfileにファイル名を記載
        context: ./web-WaNTo
        dockerfile: dockerfile.prod
    # 正常起動後に実行するコマンド
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8800
    volumes:
      # マウントするディレクトリ
      # - ./web-WaNTo:/workspace
      - static-volume:/workspace/static
    expose:
      # 指定されたポートは接続されたサービスからアクセス可能
      - 8800
    env_file:
      # 環境変数に設定するファイル
      - ./web-WaNTo/.env
    depends_on:
      # 接続するサービス
      - db

  db:
    container_name: db-wanto
    # build: ./db-WaNTo
    image: db-wanto
    volumes:
      # /var/lib/postgresql/dataにDBのデータが格納されている
      - ./db-WaNTo/wanto-data:/var/lib/postgresql/data
    env_file: 
      - ./db-WaNTo/.env
    ports:
      # ホスト側のポートはローカルのpsqlとバッティングするので5432以外にする
      - 5434:5432

  nginx:
    container_name: nginx-wanto
    # build: ./nginx-WaNTo
    image: nginx-wanto
    volumes:
      # - ./web-WaNTo/app/static:/usr/src/app/static
      - static-volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  wanto-data:
    external: 
      name: wanto-postgres 
  static-volume:
    external: 
      name: wanto-static-volume
