# Generated by Django 3.1.7 on 2021-03-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantoitem',
            name='meta_des',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
