# Generated by Django 3.1.7 on 2021-03-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca_camera', '0002_wantoitem_meta_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantoitem',
            name='meta_des',
            field=models.CharField(blank=True, help_text='Some tags text(html format) in html > head', max_length=255, null=True),
        ),
    ]
