# Generated by Django 3.1.7 on 2021-03-24 21:45

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca_camera', '0007_auto_20210325_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wantoitem',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='wantoitem',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='wantoitem',
            name='maker_name',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ca_camera.item_maker'),
        ),
    ]
