# Generated by Django 3.1.6 on 2021-02-19 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_url', models.URLField()),
                ('main_tiitle', models.CharField(max_length=200)),
                ('wantoitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wantoitem')),
            ],
        ),
        migrations.CreateModel(
            name='Except',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('except_url', models.URLField()),
                ('except_title', models.CharField(max_length=200)),
                ('wantoitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wantoitem')),
            ],
        ),
    ]
