# Generated by Django 3.1.6 on 2021-02-19 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_except_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='main_tiitle',
            new_name='main_title',
        ),
    ]
