# Generated by Django 3.1.6 on 2021-02-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210219_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='except',
            name='except_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='main',
            name='main_title',
            field=models.CharField(max_length=255),
        ),
    ]
